name: Automated Customer Retention Pipeline

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Upgraded to fix the Google API warning

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Inject GCP Credentials Secret
        env:
          GCP_CREDS: ${{ secrets.GCP_CREDENTIALS_JSON }}
        run: |
          mkdir -p config
          echo "$GCP_CREDS" > config/gcp_credentials.json

      - name: Run Main Pipeline
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: |
          python main_pipeline.py
      - name: Commit and Push Updated State
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add config/pipeline_offset.txt
          git add data/latest_alerts.csv  # Agar root folder mein hai toh sirf latest_alerts.csv likhna
          git commit -m "Auto-update pipeline offset and daily alerts [skip ci]" || echo "No changes to commit"
          git push
